### ISSUE TITLE
Where's the generator?

### ISSUE THREAD

**Issue by jmandel** [kwboone/FHIR-JSON-to-XML-Converter#2]
This is fun! But I really want to see how this 27k line beast comes to life :-)

Repo structure could look like:

```
   dist/
      convert.js (the fully built output)
   test/
      tests.js
   src/
      some tools for downloading schema files from FHIR site && 
      doing the code generation
```

For example https://github.com/jmandel/ucum.js

**Comment by kwboone** [comment]
Generator is now in the source tree, and it has been refactored as you suggested.
